/*
Code generated by Near Gothic. DO NOT EDIT.
Generated on 2022/10/19.
Manual edits may be lost when next regenerated.

Near Gothic is (C) K Cartlidge, 2022.
No rights are asserted over generated code.
*/

package main

import (
	"fmt"
	"log"
	"os"
)

var (
	port    = 3000
	version = "1.0.0"
)

func main() {
	fmt.Println()
	fmt.Printf("API v%s\n", version)
	fmt.Println()

	// Create a server.
	s := NewServer("api", port)

	// Register middleware.
	s.AddGlobalMiddleware(s.Logger)

	// Add the API endpoints.
	s.RegisterDefaultHandlers()

	// And serve.
	log.Fatalln(s.ListenAndServe())
}

// If there is an error, display it and quit.
func check(err error) {
	if err != nil {
		fmt.Println()
		fmt.Println("ERROR")
		fmt.Println(err.Error())
		fmt.Println()
		os.Exit(1)
	}
}
