/*
Code generated by Near Gothic. DO NOT EDIT.
Generated on 2022/10/19.
Manual edits may be lost when next regenerated.

Near Gothic is (C) K Cartlidge, 2022.
No rights are asserted over generated code.
*/

package connection

import (
	"context"
	"kcartlidge/api/repo/support"
	"log"

	pgx "github.com/jackc/pgx/v4/pgxpool"
)

var (
	MaxRows   = 100_000
	DebugMode = false
	CTX       = context.Background()
)

// Connection represents a connection to the database.
type Connection struct {
	connectionString string
	DB               *pgx.Pool
}

// Connect connects to and pings the database.
// Low overhead due to underlying connection pooling.
func NewConnection(connectionString string) *Connection {
	c := Connection{}
	c.Debug("DB", "Connecting")
	c.connectionString = connectionString
	ndb, err := pgx.Connect(CTX, connectionString)
	support.Check(err)
	err = ndb.Ping(CTX)
	support.Check(err)
	c.DB = ndb
	c.Debug("DB", "Connected")
	return &c
}

func (c *Connection) Debug(key string, value interface{}) {
	if DebugMode {
		log.Println(key+" : ", value)
	}
}
